package customerBookingApp;


/**
* customerBookingApp/CustomerManagerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CustomerManager.idl
* Friday, 2 August, 2019 12:23:53 AM EDT
*/

public interface CustomerManagerInterfaceOperations 
{
  String addEvent (String userId, String eventID, String eventType, String capacity);
  String removeEvent (String userId, String eID, String eType);
  String listEventAvailability (String userId, String eventType);
  void shutdown ();
  String bookEvent (String userId, String custID, String eID, String eType);
  String getBookingSchedule (String userId, String customerID);
  String cancelEvent (String userId, String customerID, String eventID, String eventType);
  String swapEvent (String userId, String custID, String newEventID, String newEventType, String oldEventID, String oldEventType);
} // interface CustomerManagerInterfaceOperations
