package customerBookingApp;


/**
* customerBookingApp/CustomerManagerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CustomerManager.idl
* Friday, 2 August, 2019 12:23:53 AM EDT
*/

public interface CustomerManagerInterface extends CustomerManagerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CustomerManagerInterface
