package customerBookingApp;


/**
* customerBookingApp/CustomerManagerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CustomerManager.idl
* Friday, 2 August, 2019 12:23:53 AM EDT
*/

public abstract class CustomerManagerInterfacePOA extends org.omg.PortableServer.Servant
 implements customerBookingApp.CustomerManagerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addEvent", new java.lang.Integer (0));
    _methods.put ("removeEvent", new java.lang.Integer (1));
    _methods.put ("listEventAvailability", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
    _methods.put ("bookEvent", new java.lang.Integer (4));
    _methods.put ("getBookingSchedule", new java.lang.Integer (5));
    _methods.put ("cancelEvent", new java.lang.Integer (6));
    _methods.put ("swapEvent", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // customerBookingApp/CustomerManagerInterface/addEvent
       {
         String userId = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String capacity = in.read_string ();
         String $result = null;
         $result = this.addEvent (userId, eventID, eventType, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // customerBookingApp/CustomerManagerInterface/removeEvent
       {
         String userId = in.read_string ();
         String eID = in.read_string ();
         String eType = in.read_string ();
         String $result = null;
         $result = this.removeEvent (userId, eID, eType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // customerBookingApp/CustomerManagerInterface/listEventAvailability
       {
         String userId = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.listEventAvailability (userId, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // customerBookingApp/CustomerManagerInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 4:  // customerBookingApp/CustomerManagerInterface/bookEvent
       {
         String userId = in.read_string ();
         String custID = in.read_string ();
         String eID = in.read_string ();
         String eType = in.read_string ();
         String $result = null;
         $result = this.bookEvent (userId, custID, eID, eType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // customerBookingApp/CustomerManagerInterface/getBookingSchedule
       {
         String userId = in.read_string ();
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (userId, customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // customerBookingApp/CustomerManagerInterface/cancelEvent
       {
         String userId = in.read_string ();
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.cancelEvent (userId, customerID, eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // customerBookingApp/CustomerManagerInterface/swapEvent
       {
         String userId = in.read_string ();
         String custID = in.read_string ();
         String newEventID = in.read_string ();
         String newEventType = in.read_string ();
         String oldEventID = in.read_string ();
         String oldEventType = in.read_string ();
         String $result = null;
         $result = this.swapEvent (userId, custID, newEventID, newEventType, oldEventID, oldEventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:customerBookingApp/CustomerManagerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CustomerManagerInterface _this() 
  {
    return CustomerManagerInterfaceHelper.narrow(
    super._this_object());
  }

  public CustomerManagerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CustomerManagerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CustomerManagerInterfacePOA
