package IDL;


/**
* IDL/IDLInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/yoges/Desktop/DSWorkspace/DS_Demo_Workspace/DEMS_Assignment2/src/idlinterface/IDLInterface.idl
* Monday, July 8, 2019 4:09:53 PM EDT
*/

public interface IDLInterface extends IDLInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IDLInterface
