package IDL;

/**
* IDL/IDLInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/yoges/Desktop/DSWorkspace/DS_Demo_Workspace/DEMS_Assignment2/src/idlinterface/IDLInterface.idl
* Monday, July 8, 2019 4:09:53 PM EDT
*/

public final class IDLInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public IDL.IDLInterface value = null;

  public IDLInterfaceHolder ()
  {
  }

  public IDLInterfaceHolder (IDL.IDLInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDL.IDLInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDL.IDLInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDL.IDLInterfaceHelper.type ();
  }

}
